export const HANDLE_INPUT_CHANGE = "HANDLE_INPUT_CHANGE";
export const HANDLE_SUBMIT_ADD_CONTACT = "HANDLE_SUBMIT_ADD_CONTACT";
export const HANDLE_CLEAR_FORM_DATA = "HANDLE_CLEAR_FORM_DATA";
export const HANDLE_SUBMIT_EDIT_CONTACT = "HANDLE_SUBMIT_EDIT_CONTACT";
export const HANDLE_DELETE_ITEM = "HANDLE_DELETE_ITEM";
